stages:
  - build

variables:
  GIT_DEPTH: 0
  DOCKER_BUILDKIT: 1
  TAG:
    value: "0.0.1-SNAPSHOT"
    description: "Docker image tag"
  BRANCH:
    value: "develop"
    description: "Branch to build from"

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

default:
  tags:
    - self-hosted

build-app:
  stage: build
  variables:
    DOCKER_IMAGE: $GITLAB_REGISTRY/portfolio-ui
  before_script:
    - |
      echo "Checking CI variables..."
      if [ -z "$GITLAB_TOKEN" ]; then echo "❌ Error: GITLAB_TOKEN is not set"; exit 1; fi
      if [ -z "$GITLAB_USERNAME" ]; then echo "❌ Error: GITLAB_USERNAME is not set"; exit 1; fi
      if [ -z "$GITLAB_REGISTRY" ]; then echo "❌ Error: GITLAB_REGISTRY is not set"; exit 1; fi
    - echo "$GITLAB_TOKEN" | docker login $GITLAB_REGISTRY -u $GITLAB_USERNAME --password-stdin
  script:
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        echo "Building from tag: $CI_COMMIT_TAG"
        BUILD_TAG=$CI_COMMIT_TAG
      elif [ "$CI_PIPELINE_SOURCE" == "web" ]; then
        echo "Building from manual trigger: Branch=$BRANCH, Tag=$TAG"
        git fetch origin $BRANCH
        git checkout $BRANCH
        BUILD_TAG=$TAG
      else
        echo "❌ Error: This pipeline only supports Tags or Manual triggers."
        exit 1
      fi
    - |
      echo "Build app to docker image"
      docker build --no-cache --platform linux/arm64 \
        --build-arg NEXT_PUBLIC_WEB_URL=$NEXT_PUBLIC_WEB_URL \
        --build-arg NEXT_PUBLIC_RESUME_URL=$NEXT_PUBLIC_RESUME_URL \
        -t $DOCKER_IMAGE:$BUILD_TAG .
      docker image ls
    - |
      echo "Push docker image to GitLab registry"
      docker push $DOCKER_IMAGE:$BUILD_TAG
    - |
      echo "Clean docker images"
      docker rmi $DOCKER_IMAGE:$BUILD_TAG
      docker image prune -f
